<a href="https://colab.research.google.com/github/NAMU578/INFSUB/blob/main/1_%EB%84%98%ED%8C%8C%EC%9D%B4_%EA%B8%B0%EC%B4%88(%EA%B0%9C%EB%85%90).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# numpy 기초

## 넘파이 모듈 불러오기

In [ ]:
import numpy as np

In [ ]:
print(np.__version__)

2.0.2


## 파이썬 리스트와 넘파이 배열 비교

In [ ]:
# 파이썬 리스트 만들기
data = [5, 9, 2.5, 3, 1]
type(data)
# print(type(data))

list

In [ ]:
# 넘파이 배열로 변환
array = np.array(data)
type(array)
# print(type(array))

numpy.ndarray

In [ ]:
# 차이점이 뭘까?
print(data)
print(array)
# print(array.dtype) # 넘파이 배열의 데이터 타입 확인

[5, 9, 2.5, 3, 1]
[5.  9.  2.5 3.  1. ]


In [ ]:
# 모든 파이썬 리스트를 넘파이 배열로 변환할 수 있을까?
# 변환했을 때 데이터 타입은?
data = [2, 1, 21, '홍길동', 90, 75, 80]
array = np.array(data)
print(data)
print(array)
print(array.dtype) # <U21 이 의미하는 것은?  유니코드

[2, 1, 21, '홍길동', 90, 75, 80]
['2' '1' '21' '홍길동' '90' '75' '80']
<U21


## 넘파이 배열 만들기
* 넘파이 배열의 차원과 모양 확인할 때 많이 사용하는 ndim 속성, shape 속성
* 넘파이 배열의 모양 변형할 때 많이 사용하는 함수: reshape()
* 넘파이 배열의 기본 데이터 타입은 float64(정수의 경우 int64)

### 0으로 채워진 배열 만들기

In [ ]:
# 0 값을 가지는 배열 만들기
one = np.zeros(10)
print(one)
print(one.ndim)
print(one.shape)
print(one.dtype)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
1
(10,)
float64


In [ ]:
two = np.zeros((5, 10))
print(two)
print(two.ndim)
print(two.shape)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
2
(5, 10)


### 1로 채워진 배열 만들기

In [ ]:
three = np.ones((2, 3, 8))
print(three)
print(three.ndim)
print(three.shape)

[[[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]]
3
(2, 3, 8)


### 정수 범위를 활용하여 배열 만들기

In [ ]:
a = np.arange(10) # 시작값(생략가능, 0), 종료값(미만), 간격(생략가능, 1)
print(a)
print(a.dtype)
a.reshape(2,5) # 모양을 2행 5열로 변형

[[0 1 2 3 4]
 [5 6 7 8 9]]
int64
2
(2, 5)


In [ ]:
# 결과가 어떻게 나올까? 생각해 보자(이건 심화에서 배울 내용이긴 함)
print(a.ndim)
print(a.shape)

1
(10,)


In [ ]:
np.arange(5, 30, 3)  # 시작값:5, 종료값:30 미만, 간격:3

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29])

In [ ]:
array_1 = np.array([1, 3, 5, 7, 9], dtype=np.float32)
array_2 = np.array([1, 3, 5, 7, 9], dtype=np.int16)

In [ ]:
array_1.dtype

dtype('float32')

In [ ]:
array_2.dtype

dtype('int16')

In [ ]:
# dtype 변경 함수 astype()
array_2_float = array_2.astype(np.float64)
array_2_float.dtype

dtype('float64')

In [ ]:
num_strings = np.array(['-3.145', '5', '8.4', '21'], dtype=np.bytes_)
num_strings.dtype
# 'S6' 데이터 타입은 뭘 의미하는 걸?? S타입(bytes_):바이트/아스키로 인코딩, 글자당 1바이트 고정, U(str_) 유니코드 인코딩, 글자당 4바이트(UTF-32), 한글 한 글자는 UTF-8기준 3바이트이므로 S타입에선 글자가 깨질 수 있음.
#UTF-8 (가변 1~4바이트)특징: 영문·숫자는 1바이트, 한글·한자는 3바이트, 이모지 등 보조 문자는 4바이트를 사용하는 가변 길이 인코딩입니다.
#장점: 영문 용량이 매우 작고 기존 아스키(ASCII) 코드와 완벽히 호환되어 현재 웹 표준으로 가장 많이 쓰입니다.
#UTF-16 (가변 2 또는 4바이트, 오타 'UTF-64'의 정정 대상)
#특징: 기본 문자(BMP)는 2바이트, 특수 문자는 4바이트(서로게이트 쌍)로 표현합니다.장점: 한글이나 한자를 주로 쓸 때 UTF-8(3바이트)보다 적은 용량(2바이트)을 차지할 때가 있습니다.
#단점: 바이트 순서(Endian)를 구분해야 하며 웹에서는 용량이 비효율적일 수 있습니다. (자바, 윈도우즈 내부 등에서 주로 사용)
#UTF-32 (고정 4바이트)
#특징: 모든 문자를 무조건 4바이트(32비트) 고정 길이로 표현합니다.장점: 글자 수가 몇 번째 위치하는지 계산하기 단순하고 접근 속도가 빠릅니다.
#단점: 영문이나 한글 할 것 없이 무조건 4바이트를 써서 메모리와 저장 공간 낭비가 가장 심합니다.

dtype('S6')

In [ ]:
num_strings = num_strings.astype(float)   # float 대신 np.float64 입력 가능
num_strings

array([-3.145,  5.   ,  8.4  , 21.   ])

In [ ]:
num_strings.dtype

dtype('float64')

## 넘파이 배열에서의 연산

In [ ]:
array_1 = np.array([[1., 2., 3., 4., 5.], [6., 7., 8., 9., 10.]])
array_2 = np.array([[1., 3., 5., 7., 9.], [2., 4., 6., 8., 10.]])

In [ ]:
array_1 * array_2

array([[  1.,   6.,  15.,  28.,  45.],
       [ 12.,  28.,  48.,  72., 100.]])

In [ ]:
array_1 - array_2

array([[ 0., -1., -2., -3., -4.],
       [ 4.,  3.,  2.,  1.,  0.]])

In [ ]:
1 / array_1

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ]])

In [ ]:
array_2 ** 0.25

array([[1.        , 1.31607401, 1.49534878, 1.62657656, 1.73205081],
       [1.18920712, 1.41421356, 1.56508458, 1.68179283, 1.77827941]])

In [ ]:
array_b = array_1 > array_2
array_b

array([[False, False, False, False, False],
       [ True,  True,  True,  True, False]])

## 넘파이 배열 슬라이싱(부분 추출)

In [ ]:
a_1d = np.arange(10, 151, 10)
a_1d

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150])

In [ ]:
a_1d[7]

np.int64(80)

In [ ]:
# 넘파이 배열 슬라이싱
a_1d[[7, 9]]

array([ 80, 100])

In [ ]:
# 자주하는 실수: 파이썬 리스트의 슬라이싱과 넘파이 배열의 슬라이싱이 다름
plist_1d = list(range(10, 151, 10))
plist_1d

[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150]

In [ ]:
# 오류 발생함
plist_1d[[7, 9]]

TypeError: list indices must be integers or slices, not list

In [ ]:
# 파이썬 리스트에서 동일한 결과를 만들려면 리스트 컴프리핸션 방법 사용
[plist_1d[i] for i in [7, 9]]

[80, 100]

In [ ]:
print(a_1d)
a_1d[:7:2] # 이 것의 의미는? range(0, 7, 2)

[ 10  20  30  40  50  60  70  80  90 100 110 120 130 140 150]


array([10, 30, 50, 70])

In [ ]:
a_1d[4:7] = 55
a_1d

array([ 10,  20,  30,  40,  55,  55,  55,  80,  90, 100, 110, 120, 130,
       140, 150])

In [ ]:
a_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a_2d[1]

array([4, 5, 6])

In [ ]:
a_2d[1,2]
# a_2d[1][2] # 넘파이에서는 같은 표현

np.int64(6)

In [ ]:
a_2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
print(a_2d)
a_2d[:2, :2]


[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 2],
       [4, 5]])

In [ ]:
# a_2d에서 다음 부분을 슬라이싱 하려면?
# 6, 9
# 8, 12

# 아래의 빈 부분을 채워 보시오.
a_2d[1:3, 1:3]

array([[5, 6],
       [8, 9]])

In [ ]:
a_2d[[0, 2], :2]

array([[1, 2],
       [7, 8]])

In [ ]:
a_2d[[0, 2]][:, [0, 2]]  #a_2d[[0, 2]]는 a_2d 배열의 0번째 행과 2번째 행을 선택하여 [[1, 2, 3], [7, 8, 9]]라는 중간 배열을 만듦.
#그 다음 [:, [0, 2]]는 이 중간 배열에서 모든 행에 대해 0번째와 2번째 열을 선택, 결과적으로 [[1, 3], [7, 9]]가 출력.

array([[1, 3],
       [7, 9]])

In [ ]:
# 이건 어떻게 나올까?
a_2d[[0, 1], [2, 0]]  #0행 2열과 1행 0열
# a_2d[[0, 1, 2], [0, 1, 2]]

array([3, 4])

넘파이 배열 `a_2d`는 다음과 같습니다:
```python
a_2d = np.array([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])
```

각 인덱싱 표현식의 차이점은 다음과 같습니다.

| 표현식                 | 설명                                                                                                                                | `a_2d` 예시 (`a_2d[1, 2]`) | 결과        | 반환 형태             |
| :--------------------- | :---------------------------------------------------------------------------------------------------------------------------------- | :------------------------- | :---------- | :-------------------- |
| `A[a, b]`              | `a`는 행 인덱스, `b`는 열 인덱스입니다. 특정 위치의 단일 요소에 직접 접근합니다.                                              | `a_2d[1, 2]`             | `6`         | 스칼라 값 (0차원)     |
| `A[a][b]`              | `A[a]`가 먼저 `a`번째 행(1차원 배열)을 선택한 다음, `[b]`로 그 1차원 배열에서 `b`번째 요소를 선택합니다. `A[a, b]`와 동일하게 동작합니다. | `a_2d[1][2]`             | `6`         | 스칼라 값 (0차원)     |
| `A[[a, b], c]`         | 고급 인덱싱입니다. `a`번째 행과 `b`번째 행을 선택한 다음, 이 선택된 각 행에서 `c`번째 열의 요소를 뽑아 1차원 배열로 반환합니다. | `a_2d[[0, 2], 0]`        | `[1, 7]`    | 1차원 배열            |
| `A[[a, b]][:, [c, d]]` | 두 단계의 인덱싱입니다. 먼저 `A[[a, b]]`로 `a`행과 `b`행을 포함하는 2차원 임시 배열을 만들고, 이 임시 배열에서 모든 행(`:`)과 `c`, `d`열을 선택합니다. | `a_2d[[0, 2]][:, [0, 2]]` | `[[1, 3], [7, 9]]` | 2차원 배열            |
| `A[[a, b], [c, d]]`    | 결합된 고급 인덱싱(coupled advanced indexing)입니다. `(a, c)`와 `(b, d)` 위치의 요소를 쌍으로 묶어 1차원 배열로 반환합니다. | `a_2d[[0, 1], [2, 0]]`   | `[3, 4]`    | 1차원 배열            |

In [ ]:
a_2d[:2, [0, 2]]  #0부터 2미만행까지 0,2번 열

array([[1, 3],
       [4, 6]])

In [ ]:
a_2d[:, :1]  #모든 행에 대해 1미만 열(0열)

array([[1],
       [4],
       [7]])

## 랜덤 관련 함수
* 랜덤 수는 코드에서 다양한 형태로 활용됨.
* 특히, 알고리즘의 성능이나 동작 상태를 평가하기 위한 무작위 데이터가 필요할 때 많이 사용됨.


In [ ]:
# 컴퓨터의 랜덤은 사실 진짜 랜덤은 아님
# 알고리즘에 의해 생성되는 의사 난수(pseudo random number)임
# 특정 seed를 사용하면 재현성 확보 가능(코딩 실습할 때 많이 사용)
np.random.seed(1000)

### 랜덤 수 생성

In [ ]:
# rand(n) : 0~1 사이 균일분포에서 실수값 랜덤 수 n개 추출
np.random.rand(5)

array([0.0351059 , 0.85505825, 0.65725351, 0.76568299, 0.55408724])

In [ ]:
np.random.rand(10)

array([0.88509294, 0.90419762, 0.0104217 , 0.07455674, 0.24462921,
       0.13330475, 0.6979251 , 0.39820488, 0.88312219, 0.18100751])

In [ ]:
# randn(n) : 정규분포(가우시안 분포, 평균:0, 표준편차: 1)에서 랜덤 수 n개 추출.
np.random.randn(10)

array([-0.32692468, -0.04579719, -0.30446006,  1.92301013, -0.078659  ,
       -0.58206572, -1.61798224,  0.86726082, -1.04043709,  0.65042142])

In [ ]:
np.random.randn(5, 3)

array([[ 2.69964586,  0.80202451, -1.09692126],
       [-0.17805445, -0.42287048, -0.33040055],
       [-1.11116278, -0.74200575,  2.57475919],
       [ 1.07321332, -1.86613451, -0.64717693],
       [ 1.08224081,  0.17667032, -0.83532823]])

In [ ]:
# randint(n, size=m) : 0~n-1 사이 정수 랜덤 수 m개 추출
np.random.randint(10, size=15)

array([7, 2, 0, 4, 4, 1, 6, 5, 1, 4, 1, 7, 4, 5, 0])

In [ ]:
# ranint(k, n, size=m) : k~n-1 사이 정수 랜덤 수 m개 추출
np.random.randint(5, 25, size=10)

array([ 7,  5, 17, 16, 15, 20, 13,  5, 24,  5])

In [ ]:
np.random.randint(5, 25, size=(3, 8))

array([[13, 21,  7, 16, 14, 18, 24, 19],
       [20, 14, 11, 23, 14, 14, 17, 24],
       [ 9, 13,  6,  8, 18, 18, 18, 12]])

In [ ]:
# 정규 분포를 따르는 난수 생성
# randn()과 차이점: randn(3,8)은 평균:0, 표준편차:1 고정한 3*8개 랜덤 수 생성
# normal()의 경우: np.random.normal(loc=10, scale=2, size=(3,8))
# 평균:10, 표준편차:2의 3*8개 랜덤 수 생성
# 즉, 평균과 표준편차 변경 가능

np.random.normal(loc=10, scale=2, size=(5, 3))
np.random.normal(size=(5, 3)) # 평균과 표준편차를 생략하면 기본은 평균:0, 표준편차:1 -> randn과 같음

array([[ 0.32912838,  0.95543026, -0.53319824],
       [ 0.52217616,  0.59446233, -1.69967712],
       [ 1.54742058, -1.20656259, -0.50259869],
       [-0.8666747 , -0.82986582,  1.1376847 ],
       [ 0.38630342,  1.07708504,  1.3548703 ]])

### 랜덤 관련 다양한 활용 함수

In [ ]:
data = np.arange(1, 21)
data

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
# shuffle(): 랜덤하게 배열의 값 섞기
np.random.shuffle(data)
data

array([ 8,  2, 20, 16,  7, 11,  4, 15, 19,  1, 13,  5, 14, 12, 10,  9, 18,
        6, 17,  3])

In [ ]:
# choice(): 랜덤 수 선택
np.random.choice(10, 5, replace=False) #중복불가, 0~9까지 중 5개

array([1, 9, 6, 0, 8])

In [ ]:
np.random.choice(10, 5, replace=True) #중복가능

array([1, 2, 0, 2, 7])

In [ ]:
np.random.choice(np.arange(5, 11), 5)  #5~10까지 중 5개

array([6, 8, 9, 9, 7])

In [ ]:
np.random.choice(3, 12, p=[0.3, 0.5, 0.2]) #0~2까지 각각 0.3, 0.5, 0.2의 확률로 랜덤 선택

array([1, 0, 2, 2, 0, 1, 0, 1, 2, 1, 1, 1])

In [ ]:
np.random.choice(['apple', 'banana', 'orange'], 8)

array(['apple', 'orange', 'orange', 'apple', 'banana', 'apple', 'banana',
       'banana'], dtype='<U6')

## 넘파이 배열 연산 관련 함수


In [ ]:
array = np.random.randint(30, size=20)
array

array([26, 13,  7,  2, 27,  9,  1, 26, 12, 17, 12,  1,  5, 16,  0, 29,  0,
        4,  2, 17])

In [ ]:
len(array)

20

In [ ]:
# 산술평균
np.mean(array)
# array.mean() # 비슷한 표현

np.float64(11.3)

In [ ]:
# 중앙값: 정렬했을 때 가운데 위치 값(데이터갯수가 짝수개일때 가운데 두개의 평균값)
np.median(array)

np.float64(10.5)

In [ ]:
# 표준편차
np.std(array)

np.float64(9.59218431849597)

In [ ]:
# 분산
np.var(array)

np.float64(92.00999999999999)

In [ ]:
np.min(array)

np.int64(0)

In [ ]:
np.max(array)

np.int64(29)

In [ ]:
array.sum()

np.int64(226)

In [ ]:
# 배열에서 주어진 축에 따라 누적되는 원소들의 누적 합을 계산하는 함수
array.cumsum()

array([ 26,  39,  46,  48,  75,  84,  85, 111, 123, 140, 152, 153, 158,
       174, 174, 203, 203, 207, 209, 226])

In [ ]:
# 배열에서 주어진 축에 따라 누적되는 원소들의 누적 곱을 계산하는 함수
array.cumprod()

array([           26,           338,          2366,          4732,
              127764,       1149876,       1149876,      29896776,
           358761312,    6098942304,   73187307648,   73187307648,
        365936538240, 5854984611840,             0,             0,
                   0,             0,             0,             0])

In [ ]:
array = np.random.randn(50)
array

array([-0.08636776, -0.39878732,  0.01315251, -0.26071818, -1.31046758,
        0.22892491, -0.56803687,  1.7882411 , -0.25899037, -0.03878802,
        0.62711477,  0.69497744, -1.34899438,  0.19435327, -0.43656128,
       -0.27515316,  1.37829854,  1.43665169, -0.9363647 , -1.17825488,
       -0.41187463,  1.14506002,  0.15964084,  0.44507351, -1.1391958 ,
       -0.14103035,  2.11273606,  0.39931225, -0.84056869,  2.46273494,
        1.08390606, -0.98328246,  0.49501135, -0.18258059,  0.71246301,
       -0.47579037, -0.22815328,  0.90755657, -1.52578909, -0.15933321,
        0.91000105, -0.71687734,  0.0135924 , -1.15539581,  0.15217385,
       -0.48261994, -0.34513673,  0.23687351,  1.08841167,  0.26833818])

In [ ]:
(array > 0).sum()  # 왜 >0인 데이터의 갯수가 출력될까?
array[array > 0].sum() # 0보다 큰 값들을 모두 더하는 sum()은 어떻게 해야 할까?

np.float64(18.954599498065818)

첫 번째 줄 (array > 0).sum()은 array 배열에서 0보다 큰 값들의 '개수'를 세는 코드. array > 0 연산을 수행하면 array의 각 요소가 0보다 큰지 여부를 나타내는 True 또는 False 값으로 구성된 불리언(boolean) 배열이 생성. NumPy에서는 True를 1로, False를 0으로 간주하므로, 이 불리언 배열에 .sum()을 적용하면 True의 개수, 즉 0보다 큰 값의 개수를 얻음.

두 번째 줄 array[array > 0].sum()은 array 배열에서 0보다 큰 값들의 '합계'를 구하는 코드. 여기서도 array > 0는 불리언 배열을 생성하지만, array[...]와 같이 인덱스로 사용될 때는 불리언 인덱싱(Boolean Indexing)이 일어남. 이는 원본 array에서 해당 불리언 배열의 값이 True인 위치의 요소들만 선택하여 새로운 배열을 만듦. 그 결과로 얻어진 새로운 배열(0보다 큰 값들만 포함된)에 .sum()을 적용하면, 0보다 큰 모든 값들의 합계를 계산.

In [ ]:
bools = np.array([1, 1, 0, 0])
bools

array([1, 1, 0, 0])

In [ ]:
bools.any()

np.True_

any() 메서드는 배열 안에 True (또는 0이 아닌) 값이 하나라도 있으면 True를 반환. bools 배열에는 1이라는 True로 간주되는 값이 포함되어 있기 때문에, bools.any()는 True를 반환.

In [ ]:
bools.all()

np.False_

In [ ]:
array = np.random.randint(20, size=10)
array

array([12, 16,  3, 14,  5,  0, 19, 10, 19,  0])

In [ ]:
array.sort()

In [ ]:
array

array([ 0,  0,  3,  5, 10, 12, 14, 16, 19, 19])

In [ ]:
fruits = np.array(['kiwi', 'apple', 'kiwi', 'lemon', 'apple', 'banana', 'banana', 'lemon'])
fruits

array(['kiwi', 'apple', 'kiwi', 'lemon', 'apple', 'banana', 'banana',
       'lemon'], dtype='<U6')

In [ ]:
np.unique(fruits) #중복 제거해 순서대로

array(['apple', 'banana', 'kiwi', 'lemon'], dtype='<U6')

In [ ]:
numbers = np.array([5 ,7, 1, 2, 1, 7, 8, 5])
numbers

array([5, 7, 1, 2, 1, 7, 8, 5])

In [ ]:
np.unique(numbers)

array([1, 2, 5, 7, 8])